projects:
  camhercxp:
    schemaPath: amplify/backend/api/camhercxp/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
